//! The peer wire's frame envelope (`docs/protocol/peer-wire-spec.md` §1.2):
//! a length-prefixed frame carrying an OER-encoded ILP packet, shared by
//! [`crate::NetworkPeerTransport`] (the dialing side) and
//! [`crate::PeerWireServer`] (the accepting side) so both read and write
//! exactly the same bytes on the wire.
//!
//! Claims, fees, minimum delivery, FLUSH and CLAIM_ACK (§3-§5) are not
//! implemented here -- nothing in `connector-domain`'s packet types carries
//! those fields yet (they land with issues #417/#418), so this framing only
//! ever carries a bare PREPARE/FULFILL/REJECT, matching what the packet
//! plane can actually produce today.

use tokio::io::{AsyncReadExt, AsyncWriteExt};

pub const FRAME_TYPE_PREPARE: u8 = 0x01;
pub const FRAME_TYPE_FULFILL: u8 = 0x02;
pub const FRAME_TYPE_REJECT: u8 = 0x03;

const CORRELATION_ID_LEN: usize = 16;

/// Protects both sides from unbounded buffering (§1.2): a `length` beyond
/// this is a transport-level failure, not a payload to keep reading.
const MAX_FRAME_LEN: u32 = 16 * 1024 * 1024;

/// One frame on the wire: `frameType` + `correlationId` + length-prefixed
/// `payload` (§1.2). `correlationId` is generated by the sender of a PREPARE
/// and echoed on the FULFILL/REJECT answering it.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Frame {
    pub frame_type: u8,
    pub correlation_id: [u8; CORRELATION_ID_LEN],
    pub payload: Vec<u8>,
}

pub async fn write_frame<W: AsyncWriteExt + Unpin>(
    writer: &mut W,
    frame: &Frame,
) -> std::io::Result<()> {
    writer.write_u8(frame.frame_type).await?;
    writer.write_all(&frame.correlation_id).await?;
    writer.write_u32(frame.payload.len() as u32).await?;
    writer.write_all(&frame.payload).await?;
    writer.flush().await
}

pub async fn read_frame<R: AsyncReadExt + Unpin>(reader: &mut R) -> std::io::Result<Frame> {
    let frame_type = reader.read_u8().await?;

    let mut correlation_id = [0u8; CORRELATION_ID_LEN];
    reader.read_exact(&mut correlation_id).await?;

    let length = reader.read_u32().await?;
    if length > MAX_FRAME_LEN {
        return Err(std::io::Error::new(
            std::io::ErrorKind::InvalidData,
            format!("frame length {length} exceeds the maximum {MAX_FRAME_LEN}"),
        ));
    }

    let mut payload = vec![0u8; length as usize];
    reader.read_exact(&mut payload).await?;

    Ok(Frame {
        frame_type,
        correlation_id,
        payload,
    })
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::io::Cursor;

    #[tokio::test]
    async fn a_frame_round_trips_through_write_and_read() {
        let frame = Frame {
            frame_type: FRAME_TYPE_PREPARE,
            correlation_id: [7u8; CORRELATION_ID_LEN],
            payload: b"hello".to_vec(),
        };

        let mut buf = Vec::new();
        write_frame(&mut buf, &frame).await.unwrap();

        let decoded = read_frame(&mut Cursor::new(buf)).await.unwrap();
        assert_eq!(decoded, frame);
    }

    #[tokio::test]
    async fn read_frame_rejects_a_length_beyond_the_maximum() {
        let mut buf = Vec::new();
        buf.push(FRAME_TYPE_PREPARE);
        buf.extend_from_slice(&[0u8; CORRELATION_ID_LEN]);
        buf.extend_from_slice(&(MAX_FRAME_LEN + 1).to_be_bytes());

        let result = read_frame(&mut Cursor::new(buf)).await;
        assert!(result.is_err());
    }
}
