# Production Single-Node ILP Connector Configuration
#
# This is a production-hardened configuration template for a single ILP connector.
# Unlike development configurations, this template:
# - Uses INFO-level structured JSON logging (not DEBUG/pretty-printed)
# - Loads all secrets from environment variables (not hardcoded in YAML)
# - Contains minimal configuration (peers/routes added as needed)
# - Follows production security best practices
#
# Usage:
#   1. Run the onboarding wizard: npx @m2m/connector setup
#      OR copy .env.example to .env and edit manually
#   2. Add peers to the peers array below (if needed)
#   3. Add routes to the routes array below (if needed)
#   4. Deploy with: docker compose -f docker-compose-production.yml up -d
#
# Security Notes:
#   - NEVER hardcode secrets in this file
#   - ALL BTP authentication tokens MUST be in .env file
#   - This file is committed to git, .env is NOT
#   - Use environment variable pattern: ${BTP_PEER_<PEER_ID>_SECRET}

# =============================================================================
# Node Identity
# =============================================================================
# This identifies the connector in the ILP network.
# Override with NODE_ID environment variable.
nodeId: production-connector

# ILP address prefix for this connector
# This is used for routing and peer discovery
ilpAddress: g.connector.mynode

# =============================================================================
# Network Configuration
# =============================================================================
# BTP Server Configuration
# The connector will listen for incoming BTP connections on this port.
# Override with BTP_SERVER_PORT environment variable.
btpServerPort: 4000

# Health Check Configuration
# HTTP endpoint for Docker health checks and monitoring.
# Override with HEALTH_CHECK_PORT environment variable.
healthCheckPort: 8080

# =============================================================================
# Settlement Configuration
# =============================================================================
# Settlement preference: 'evm' | 'xrp' | 'both'
# Override with SETTLEMENT_PREFERENCE environment variable.
settlementPreference: both

# Blockchain RPC endpoints
# Override with BASE_RPC_URL and XRPL_WSS_URL environment variables.
# evmRpcUrl: https://mainnet.base.org
# xrplWssUrl: wss://xrplcluster.com

# =============================================================================
# Logging Configuration
# =============================================================================
# Level: info (no debug logs in production)
# Format: json (structured logging for log aggregation)
# Override with LOG_LEVEL environment variable.
logLevel: info

# =============================================================================
# Peer Discovery Configuration (Optional)
# =============================================================================
# Enable automatic peer discovery for joining the network.
# Override with environment variables.
peerDiscovery:
  enabled: false  # PEER_DISCOVERY_ENABLED
  broadcastInterval: 60  # Seconds between broadcasts
  # discoveryEndpoints:  # PEER_DISCOVERY_ENDPOINTS (comma-separated)
  #   - http://discovery.example.com:9999
  # announceAddress: ws://my-connector.example.com:4000  # PEER_ANNOUNCE_ADDRESS

# =============================================================================
# Peer Connections (BTP Clients)
# =============================================================================
# Add BTP peers here as you configure them.
# CRITICAL: Authentication tokens MUST be environment variables, NOT hardcoded.
#
# Peer relationship types:
# - parent: Upstream connector (receives packets from us)
# - child: Downstream connector (sends packets to us)
# - peer: Symmetric relationship (bidirectional routing)
#
# Example peer configuration (uncomment and modify as needed):
# peers:
#   - id: upstream-hub
#     relation: parent
#     url: ws://hub.example.com:4000
#     authToken: ${BTP_PEER_UPSTREAM_HUB_SECRET}
#     maxPacketAmount: 1000000000000  # Max amount per packet (optional)
#
#   - id: downstream-merchant
#     relation: child
#     url: ws://merchant.example.com:4000
#     authToken: ${BTP_PEER_DOWNSTREAM_MERCHANT_SECRET}
#
#   - id: partner-connector
#     relation: peer
#     url: ws://partner.example.com:4000
#     authToken: ${BTP_PEER_PARTNER_CONNECTOR_SECRET}

# Empty peers array by default (single node with no outgoing connections)
# Add peers as needed following the pattern above
peers: []

# =============================================================================
# Routing Table
# =============================================================================
# Add routes here to direct ILP packets to the appropriate next hop.
#
# Route explanation:
# - prefix: ILP address prefix to match (g.connector.x matches all addresses starting with this)
# - nextHop: Peer ID to forward packets to (must match a peer ID above, or own nodeId for local)
# - priority: Lower priority wins (0 is highest priority)
#
# Example route configuration (uncomment and modify as needed):
# routes:
#   - prefix: g.connector.hub
#     nextHop: upstream-hub
#     priority: 0
#   - prefix: g.connector.merchant
#     nextHop: downstream-merchant
#     priority: 0
#   - prefix: g.connector.partner
#     nextHop: partner-connector
#     priority: 0

# Default route to self (single node)
routes:
  - prefix: g.connector.mynode
    nextHop: production-connector
    priority: 0

# =============================================================================
# Monitoring Configuration (Optional)
# =============================================================================
# Prometheus metrics are enabled by default.
# Override with PROMETHEUS_ENABLED environment variable.
monitoring:
  prometheusEnabled: true
  # OpenTelemetry tracing (optional)
  # otlpEndpoint: http://jaeger:4318  # OTEL_EXPORTER_OTLP_ENDPOINT
