#!/bin/bash
# Deploy contracts to local Anvil and output addresses
# Uses Docker to run Foundry since it may not be installed locally

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(dirname "$SCRIPT_DIR")"
CONTRACTS_DIR="$PROJECT_ROOT/packages/contracts"

# Default Anvil RPC URL (use host.docker.internal for Docker-to-host communication)
ANVIL_RPC="${ANVIL_RPC_URL:-http://host.docker.internal:8545}"

echo "Deploying contracts to $ANVIL_RPC..."

# Run forge in Docker container with Foundry
OUTPUT=$(docker run --rm \
    -v "$CONTRACTS_DIR:/app" \
    -w /app \
    --add-host=host.docker.internal:host-gateway \
    ghcr.io/foundry-rs/foundry:latest \
    forge script script/DeployLocal.s.sol --rpc-url "$ANVIL_RPC" --broadcast 2>&1)

echo "$OUTPUT"

# Extract addresses from output
AGENT_TOKEN=$(echo "$OUTPUT" | grep "AGENT_TOKEN_ADDRESS=" | sed 's/.*AGENT_TOKEN_ADDRESS=//')
TOKEN_NETWORK=$(echo "$OUTPUT" | grep "TOKEN_NETWORK_ADDRESS=" | sed 's/.*TOKEN_NETWORK_ADDRESS=//')

if [ -z "$AGENT_TOKEN" ] || [ -z "$TOKEN_NETWORK" ]; then
    echo "ERROR: Failed to extract contract addresses"
    exit 1
fi

echo ""
echo "=== Contract Addresses ==="
echo "AGENT_TOKEN_ADDRESS=$AGENT_TOKEN"
echo "TOKEN_NETWORK_ADDRESS=$TOKEN_NETWORK"

# Output for shell sourcing
cat > "$PROJECT_ROOT/.env.contracts" << EOF
# Auto-generated by deploy-local-contracts.sh
AGENT_TOKEN_ADDRESS=$AGENT_TOKEN
TOKEN_NETWORK_ADDRESS=$TOKEN_NETWORK
EOF

echo ""
echo "Contract addresses saved to .env.contracts"
