// ---------------------------------------------------------------------------
// Mina USDC faucet — admin-mint of the devnet USDC token (o1js zk-proving)
// ---------------------------------------------------------------------------
// Unlike the native-MINA drip (`mina.js`, signed client-side with mina-signer,
// NO proving), minting USDC on Mina requires o1js zk-PROVING: both
// `FungibleToken.mint` and `FungibleTokenAdmin.canMint` are o1js `@method`s, so
// the mint tx must `tx.prove()`. There is NO signature-only mint path. We
// admin-mint directly from the mint AUTHORITY (the `adminPublicKey` set at
// deploy) — the simplest funding primitive for a devnet mock, mirroring the
// Solana treasury's USDC transfer.
//
// ── Why this module is a pure-ESM `.mjs` importing a COMPILED ESM build ───────
// o1js is a DUAL package: an ESM `import` resolves `o1js/dist/node/index.js`
// while a CJS `require` resolves `o1js/dist/node/index.cjs` — DIFFERENT module
// instances. The mint path MUST keep o1js as a SINGLE instance: the compiled
// circuit cache and `FungibleToken._provers` live as per-instance static state,
// and a proof generated against one instance is meaningless to another. A
// pure-ESM Node process on glibc loads o1js + mina-fungible-token ONCE and
// compiles both contracts in ~6s (verified); the ESM/CJS split (e.g. ts-node,
// or an ESM module importing the package's CommonJS `dist/`) is exactly what
// breaks the single-instance requirement.
//
// So we do NOT import the mina-zkapp package's default CommonJS `dist/`, and we
// do NOT import the `.ts` sources (the faucet has no TS transform). Instead we
// import the package's parallel ESM build (`dist-esm/`, produced by
// `packages/mina-zkapp/scripts/build-esm.mjs` at image-build time). That keeps
// exactly one o1js instance shared between this module and the token classes.
//
// The deployed USDC owner is the `UsdcChannelToken` SUBCLASS (its on-chain
// verification key is the subclass's), so mint proofs MUST be generated by
// compiling `UsdcChannelToken` (+ `FungibleTokenAdmin`) — NOT stock
// `FungibleToken`. The mint core itself mirrors `tools/mina/fund-usdc.ts`
// `mintUsdc()` (kept tiny and inlined below so this ESM module needs no CJS
// CLI script at runtime).
//
// Graceful degradation: when MINA_USDC_ADMIN_KEY / MINA_USDC_TOKEN /
// MINA_USDC_ADMIN_CONTRACT are unset, `createMinaUsdcMinter()` returns null and
// the route keeps dripping native MINA only (mirrors createSolanaFaucet /
// createMinaFaucet). Fail-loud ONLY on a structurally invalid admin key.

import { AccountUpdate, Mina, PrivateKey, PublicKey, TokenId, UInt64, fetchAccount } from 'o1js';

// Compiled ESM build of the repo's mina-zkapp token classes (see header). The
// Dockerfile builds `packages/mina-zkapp/dist-esm/` and the image lays it out so
// this relative path resolves at runtime (../../mina-zkapp/dist-esm/*).
import {
  FungibleToken,
  FungibleTokenAdmin,
  ONE_USDC,
} from '../../mina-zkapp/dist-esm/usdc-token.js';
import { UsdcChannelToken } from '../../mina-zkapp/dist-esm/usdc-channel-token.js';

const MINA_GRAPHQL_URL =
  process.env.MINA_GRAPHQL_URL || 'https://api.minascan.io/node/devnet/v1/graphql';

// Whole USDC minted per drip (scaled to 6-dp base units below). Default 1000 to
// match the Solana faucet's USDC drip.
const MINA_USDC_AMOUNT = process.env.MINA_USDC_AMOUNT || '1000';

/**
 * zkApp tx fee (nanomina). A zkApp command on the public Mina devnet is rejected
 * "Insufficient fee" at the default fee floor that `Mina.transaction` would pick
 * (proof commands cost more than plain payments). 0.1 MINA is the well-worn
 * devnet zkApp fee. Override with MINA_TX_FEE (whole MINA). 1 MINA = 1e9 nano.
 * Mirrors `tools/mina/fund-usdc.ts` MINT_FEE_NANOMINA.
 */
const MINT_FEE_NANOMINA = (() => {
  const whole = process.env.MINA_TX_FEE;
  if (whole && Number.isFinite(Number(whole))) {
    const [w, f = ''] = String(whole).split('.');
    return BigInt(w || '0') * 1_000_000_000n + BigInt((f + '000000000').slice(0, 9) || '0');
  }
  return 100_000_000n; // 0.1 MINA
})();

// Mina B62 public keys are base58check, "B62q"-prefixed (same check as mina.js).
function isValidMinaAddress(address) {
  return typeof address === 'string' && /^B62q[1-9A-HJ-NP-Za-km-z]{48,55}$/.test(address);
}

async function minaGraphql(query, variables) {
  const res = await fetch(MINA_GRAPHQL_URL, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({ query, variables }),
  });
  if (!res.ok) {
    throw new Error(`Mina GraphQL HTTP ${res.status}: ${await res.text()}`);
  }
  const body = await res.json();
  if (body.errors && body.errors.length) {
    throw new Error(`Mina GraphQL error: ${body.errors.map((e) => e.message).join('; ')}`);
  }
  return body.data;
}

/**
 * Does `recipient` already hold a token account under `tokenId`?
 *
 * Decides `fundRecipient`: the recipient's USDC token account must be CREATED
 * (paying a 1 MINA account-creation fee from the admin authority) on the FIRST
 * mint, and must NOT be re-created on subsequent mints (that errors "account
 * already exists"). We query the recipient's account under the token id; a null
 * account means it doesn't exist yet → fund it.
 *
 * Returns true when the account exists (so fundRecipient = !exists).
 */
async function tokenAccountExists(recipientB58, tokenIdField) {
  const data = await minaGraphql(
    `query TokenAcct($pk: PublicKey!, $token: TokenId!) {
      account(publicKey: $pk, token: $token) { balance { total } }
    }`,
    { pk: recipientB58, token: tokenIdField }
  );
  return !!data?.account;
}

/**
 * Admin-mint `wholeUsdc` USDC (whole tokens, scaled to 6-dp base units) to
 * `recipient`. The admin authority signs + pays fees (and the recipient's
 * token-account creation fee on first mint). Mirrors fund-usdc.ts `mintUsdc()`.
 *
 * Returns the recipient's post-mint balance (base units) as a string.
 */
async function mintUsdc({ token, feePayer, recipient, wholeUsdc, signers, fundRecipient }) {
  const amount = UInt64.from(wholeUsdc * ONE_USDC);
  const tx = await Mina.transaction(
    { sender: feePayer, fee: UInt64.from(MINT_FEE_NANOMINA) },
    async () => {
      if (fundRecipient) AccountUpdate.fundNewAccount(feePayer, 1);
      await token.mint(recipient, amount);
    }
  );
  await tx.prove();
  await tx.sign(signers).send();
  return (await token.getBalanceOf(recipient)).toString();
}

// Returns a USDC minter object, or null if USDC minting is not configured for
// this deploy (MINA_USDC_ADMIN_KEY / MINA_USDC_TOKEN / MINA_USDC_ADMIN_CONTRACT
// unset). Mirrors createSolanaFaucet / createMinaFaucet's null-when-unconfigured
// shape so an unconfigured deploy still boots.
//
// Throws (fail-loud) only when an admin key IS configured but is structurally
// not a valid base58 Mina private key — operator misconfiguration we must not
// paper over. (We never log the key.)
export function createMinaUsdcMinter() {
  const adminKeyRaw = process.env.MINA_USDC_ADMIN_KEY;
  const tokenAddr = process.env.MINA_USDC_TOKEN;
  const adminContractAddr = process.env.MINA_USDC_ADMIN_CONTRACT;

  if (!adminKeyRaw || !tokenAddr || !adminContractAddr) {
    console.log(
      'ℹ️  Mina USDC mint disabled: set MINA_USDC_ADMIN_KEY + MINA_USDC_TOKEN + ' +
        'MINA_USDC_ADMIN_CONTRACT to enable (native MINA still drips).'
    );
    return null;
  }

  // Parse the admin authority private key WITHOUT echoing it (or the raw error,
  // which may embed it).
  let adminAuthority;
  try {
    adminAuthority = PrivateKey.fromBase58(adminKeyRaw);
  } catch {
    throw new Error('MINA_USDC_ADMIN_KEY is not a valid base58 Mina private key.');
  }
  const adminPubKey = adminAuthority.toPublicKey();

  // Validate token / admin-contract addresses (fail-loud on a bad address).
  let tokenPubKey;
  let adminContractPubKey;
  try {
    tokenPubKey = PublicKey.fromBase58(tokenAddr);
    adminContractPubKey = PublicKey.fromBase58(adminContractAddr);
  } catch {
    throw new Error(
      'MINA_USDC_TOKEN / MINA_USDC_ADMIN_CONTRACT is not a valid base58 Mina address.'
    );
  }

  const wholeUsdc = BigInt(MINA_USDC_AMOUNT);

  // Bind the Mina network instance ONCE. The token instance + its tokenId are
  // derived once and reused; compilation is cached (see compileOnce below).
  const Network = Mina.Network({ mina: MINA_GRAPHQL_URL });
  Mina.setActiveInstance(Network);
  const token = new UsdcChannelToken(tokenPubKey);
  const derivedTokenId = token.deriveTokenId();
  // Decimal string for display / the /api/info capability descriptor (mirrors how
  // deploy-lightnet-zkapps.mjs records tokenId).
  const tokenIdField = derivedTokenId.toString();
  // Base58-encoded tokenId for the Mina GraphQL `TokenId!` scalar (the account
  // balance probe). Mina GraphQL expects the base58 encoding, NOT the decimal
  // Field string — a decimal value silently fails the lookup, so the probe would
  // always fall back to fundRecipient=true. Use TokenId.toBase58 for the query.
  const tokenIdBase58 = TokenId.toBase58(derivedTokenId);

  console.log('✅ Mina USDC mint enabled (admin-mint via o1js proving)');
  console.log(`   Mint authority: ${adminPubKey.toBase58()}`);
  console.log(`   Token:          ${tokenAddr}`);
  console.log(`   Admin contract: ${adminContractAddr}`);
  console.log(`   Token id:       ${tokenIdField}`);
  console.log(`   Per drip:       ${MINA_USDC_AMOUNT} USDC`);
  console.log(`   GraphQL:        ${MINA_GRAPHQL_URL}`);

  // Compile FungibleTokenAdmin + UsdcChannelToken EXACTLY ONCE. Cached via this
  // promise so concurrent/repeat mints never recompile. We compile the SUBCLASS
  // (its `compile()` override also mirrors provers onto the base FungibleToken so
  // inherited `mint` proves — see usdc-channel-token.ts).
  //
  // TIMING (issue #348): compilation takes ~6s on a dev machine but ~3 MINUTES
  // (178.6s observed) on the 2 GB devnet box — far longer than faucet clients
  // wait. So index.js WARMS this cache in the background at boot via `compile()`
  // below, and the /api/mina route checks `isWarm()` to avoid holding a drip
  // response hostage to an in-flight compile.
  let compilePromise = null;
  let warm = false;
  function compileOnce() {
    if (!compilePromise) {
      compilePromise = (async () => {
        console.log(
          '  ⏳ Compiling FungibleTokenAdmin + UsdcChannelToken circuits ' +
            '(~6s on a dev machine, ~3min on the 2 GB devnet box)...'
        );
        const t0 = Date.now();
        await FungibleTokenAdmin.compile();
        await UsdcChannelToken.compile();
        warm = true;
        console.log(
          `  ✅ Mina USDC circuits compiled in ${((Date.now() - t0) / 1000).toFixed(1)}s`
        );
      })().catch((err) => {
        // Reset so a transient compile failure can be retried on the next mint.
        compilePromise = null;
        throw err;
      });
    }
    return compilePromise;
  }

  return {
    mintAuthority: adminPubKey.toBase58(),
    token: tokenAddr,
    adminContract: adminContractAddr,
    tokenId: tokenIdField,
    graphqlUrl: MINA_GRAPHQL_URL,
    usdcAmount: MINA_USDC_AMOUNT,

    isValidAddress: isValidMinaAddress,

    // Eagerly warm the circuit cache — index.js calls this in the background at
    // boot so the first drip does not pay the ~3min on-box compile (issue #348).
    compile: compileOnce,

    // True once the circuits are compiled: a mint will run at "prove speed"
    // (~75s on the devnet box) instead of compile+prove (~4min). The route uses
    // this to decide whether to await the mint or answer with usdc.pending.
    isWarm: () => warm,

    /**
     * Admin-mint `whole` USDC (default the configured per-drip amount) to
     * `recipientB58`. Detects whether the recipient's token account exists to
     * decide fundRecipient; if detection is inconclusive we default to funding
     * and, on an "already exists" failure, retry once with fundRecipient=false.
     *
     * Returns { hash, amount } when a tx hash is available, else { amount }.
     */
    async mint(recipientB58, whole) {
      const amountWhole = whole == null ? wholeUsdc : BigInt(whole);
      await compileOnce();

      // Refresh the o1js account cache before EVERY mint (issue #348): the
      // Mina.Network instance caches fetched accounts, so without this the
      // SECOND mint in a process built its tx with the fee payer's STALE nonce
      // from the first mint's fetch and the node rejected it "Invalid_nonce"
      // (observed live on the devnet box). Also refresh the token + admin
      // zkApp accounts so the proof runs against current on-chain state.
      await fetchAccount({ publicKey: adminPubKey });
      await fetchAccount({ publicKey: tokenPubKey });
      await fetchAccount({ publicKey: adminContractPubKey });

      // Decide fundRecipient by detecting the recipient's token account. If the
      // GraphQL probe itself fails we DEFAULT to funding (true) and rely on the
      // "already exists" retry below.
      let fundRecipient = true;
      try {
        fundRecipient = !(await tokenAccountExists(recipientB58, tokenIdBase58));
      } catch (probeErr) {
        console.log(
          `  ⚠️  Could not probe recipient token account (${probeErr.message}); ` +
            'defaulting fundRecipient=true with already-exists fallback.'
        );
      }

      const recipient = PublicKey.fromBase58(recipientB58);
      const doMint = (fund) =>
        mintUsdc({
          token,
          feePayer: adminPubKey,
          recipient,
          wholeUsdc: amountWhole,
          signers: [adminAuthority],
          fundRecipient: fund,
        });

      let balance;
      try {
        balance = await doMint(fundRecipient);
      } catch (err) {
        // If we tried to fund an account that already exists, retry without.
        if (fundRecipient && /already exists|account_already_exists/i.test(String(err?.message))) {
          console.log('  ↺ Recipient token account already exists; retrying mint without funding.');
          balance = await doMint(false);
        } else {
          throw err;
        }
      }

      console.log(
        `  📤 Minted ${amountWhole} USDC to ${recipientB58} (balance ${balance} base units)`
      );
      return { amount: String(amountWhole), balance, token: tokenAddr, tokenId: tokenIdField };
    },
  };
}

// Capability descriptor fragment surfaced via mina.js's minaInfo. `minter` is the
// live createMinaUsdcMinter() (or null when unconfigured).
export function minaUsdcInfo(minter) {
  if (!minter) {
    return { usdcMint: false };
  }
  return {
    usdcMint: true,
    usdcAmount: String(minter.usdcAmount),
    usdcToken: minter.token,
    usdcTokenId: minter.tokenId,
    mintAuthority: minter.mintAuthority,
  };
}
